//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServicesDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Designation
    {
        public int id { get; set; }
        public string title { get; set; }
        public decimal minSalary { get; set; }
        public Nullable<decimal> maxSalary { get; set; }
    }
}
